name: Matt Herrmann Design
favicon: null
layout_spectrum: 0.7499
typography_spectrum: 0.4029808680061251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#555a5e'
    - '#d9d4d0'
    - '#020100'
    - '#221f1a'
  brandStrength: 0
  lightness: 0.3475196501240134
  saturation: 0.45387491630390286
  rhythmicContrast: 0.6259580384939909
purpose: []
